name=experimentersJr
version=1.0.0
author=Junior Silva Souza
maintainer=Junior Silva Souza
sentence=Biblioteca para a manutenção de um arcabouço de funcionalidades implementadas
paragraph=Exemplo de criação de uma biblioteca para Arduino e variantes.
category=Other
url=https://github.com/seuusuario/MinhaBiblioteca
architectures=*